BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBXXXXXXBBBBBBBB

BBBBB BBBBBBB
    XXXXXXXXXXXXXXX

    XXXXX XXXXXXXXBBB BBBBBBBBX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXBB BBBBBBBBBBBB XXXXXXXXBBBBBX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX

    BB BBBBBBBBBBBBBB
        XXXX
            BBB BBBBBB BB BBBBBBBBBBBBBB
                XXXX
                    XXXXXX XXXXXXBBBBBBB BBBBBBXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBB
                        
                    BBBBB
                XXXXX
            BBBBBB
        XXXXX

        BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBXXXXXXXFFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB

        BB BBBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBXXXXXXXFFFFFFFFFXXXXXXXXXXXXXXXXXXXX
        BBBBB
    BBBB BBBBBBBBBBBB
        XX XXXXXXX XXXXX
    BBBBB
BBBBBBBB
